name: Generate and Push Data

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Generate DB and Sitemaps
        run: python generate.py

      - name: Config Git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Commit and Push DB
        run: |
          git checkout --orphan database
          git reset
          git add db.json
          git commit -m "Update db.json"
          git push --set-upstream origin database --force

      - name: Commit and Push Sitemap
        run: |
          git checkout --orphan sitemap
          git reset
          git add sitemap.xml
          git commit -m "Update sitemap.xml"
          git push --set-upstream origin sitemap --force

      - name: Dispatch event to main repository
        env:
          REPOSITORY_ACCESS_TOKEN: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}
          EVENT: data-update
          REPO: GuangChen2333/CanWeTalkSimply
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ REPOSITORY_ACCESS_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/${{ REPO }}/dispatches \
          -d '{"event_type": "${{ EVENT }}"}'
